repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.0.0-alpha.6' # Use the sha or tag you want to point at
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.36.0' # Use the sha / tag you want to point at
    hooks:
      - id: eslint
